poudriere_task:
  env:
    GITHUB_TOKEN: ENCRYPTED[!a330bd1134ffd9c9fe13b7ab0fe920dc12c19d297efb0ac3c5492b3d7f1755fcdc05fdf702ad0748c07880abba88419d!]
    PORTS_BRANCH: main

  freebsd_instance:
    image_family: freebsd-15-0-snap

  install_dependencies_script:
    - pkg install -y git poudriere-devel jq

  configure_poudriere_script:
    - cp -a poudriere.d/* /usr/local/etc/poudriere.d

  create_poudriere_jail_script:
    - poudriere jail -c -j router -m git+http -v router -K Router

  create_ports_tree_script:
    - poudriere ports -c -B main -p latest

  build_ports_script:
    - poudriere bulk -j router -b latest -p latest -f router-latest-pkglist

  create_router_image_script:
    - poudriere image -t zfs -j router -s 4g -p latest -h router.home -n router -f router-latest-pkglist -c overlaydir -B pre-script.sh

  create_router_be_script:
    - poudriere image -t zfs+send+be -j router -s 4g -p latest -h router.home -n router -f router-latest-pkglist -c overlaydir -B pre-script.sh

# prepare_artifacts_script:
#   - mkdir $CIRRUS_WORKING_DIR/router
#   - cp /usr/local/poudriere/data/images/router.img router
#   - cp /usr/local/poudriere/data/images/router.be.zfs router
#   - xz -9 router/router.img
#   - xz -9 router/router.be.zfs

# upload_to_github_script:
#   - sh .cirrus/upload_to_github.sh

# router_artifacts:
#   path: router/**
